<?php

// RabbitMQ 消费者 练习
// 注册 在config下的console.php配置文件添加 'consumer' => 'app\command\Consumer'
// 使用 进入项目 www.ruiwen.com/ 然后 php think consumer
namespace app\common\command\swoole;

use app\common\lib\classes\rabbitmq\RabbitMqConnection;
use function \Swoole\Coroutine\run;
use \Swoole\Coroutine\Client;
use think\console\Command;
use think\console\Input;
use think\console\Output;
use think\facade\Log;

class TCPClient extends Command
{
    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
        $this->setName('tcp_client');
    }

    protected function execute(Input $input, Output $output)
    {
        run(function () {
            $client = new Client(SWOOLE_SOCK_TCP);
            if (!$client->connect(config('app.swoole.host'), config('app.swoole.port'), 0.5)) {
                // 连接失败时显示的信息
                echo "connect failed. Error: {$client->errCode}\n";
            }
            // 向服务端发送消息
            $client->send("hello world\n");
            echo $client->recv();
            $client->close();
        });
    }

}
